name: flagsmith_storage
description: >-
  Persistant storage for Flagsmith Client  https://www.flagsmith.com/, Flagsmith
  is 100% Open Source. Host yourself or let us take care of the hosting.

version: 4.0.0
homepage: https://github.com/Flagsmith/flagsmith-flutter-sharedpreferences
repository: https://github.com/Flagsmith/flagsmith-flutter-sharedpreferences
issue_tracker: https://github.com/Flagsmith/flagsmith-flutter-sharedpreferences/issues

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  collection: ">=1.15.0 <1.18.0"
  flagsmith_flutter_core: ^3.0.0
  flutter:
    sdk: flutter
  shared_preferences: ">=2.0.10 <=2.1.0"
dev_dependencies:
  flutter_lints: ">=1.0.0 <2.1.0"
  flutter_test:
    sdk: flutter
  platform: ^3.1.0
# The following section is specific to Flutter.
flutter: null
